version: '3.8'

services:
  airbyte-server:
    image: airbyte/airbyte-server:latest
    container_name: airbyte-server
    ports:
      - "8000:8000"
    environment:
      - AIRBYTE_LOG_LEVEL=INFO

  airbyte-scheduler:
    image: airbyte/airbyte-scheduler:latest
    container_name: airbyte-scheduler
    depends_on:
      - airbyte-server
    environment:
      - AIRBYTE_SERVER_HOST=airbyte-server
      - AIRBYTE_SERVER_PORT=8000

  airbyte-webapp:
    image: airbyte/airbyte-webapp:latest
    container_name: airbyte-webapp
    ports:
      - "8001:8001"
    depends_on:
      - airbyte-server
    environment:
      - AIRBYTE_API_URL=http://airbyte-server:8000

  dagster:
    image: dagster/dagster:latest
    container_name: dagster
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
      - ./workspace:/opt/dagster/workspace
    command: dagster-daemon run

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse

  clickhouse-client:
    image: clickhouse/clickhouse-client:latest
    container_name: clickhouse-client
    depends_on:
      - clickhouse-server
    entrypoint: ["sleep", "infinity"]

networks:
  default:
    driver: bridge