name: Deploy to server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.IP_ADDRESS }} << 'EOF'

            mkdir -p ~/deployment && cd ~/deployment

            if [ ! -d "repo" ]; then
              git clone https://<your-repo-url>.git repo
            fi

            cd repo

            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}

            cd helm

            # Deploy Airbyte
            helm upgrade --install airbyte airbyte/airbyte --namespace airbyte --create-namespace -f airbyte-values.yml

            # Deploy Dagster
            helm upgrade --install dagster dagster/dagster --namespace dagster --create-namespace -f dagster-values.yml

            # Deploy ClickHouse
            helm upgrade --install clickhouse altinity/clickhouse-operator --namespace clickhouse --create-namespace -f clickhouse-values.yml
          EOF